---
- name: Install Sway
  become: true
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  with_items:
    - sway

- name: Install Sway Extras
  become: true
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  with_items:
    - wayland
    - xorg-xwayland
    - seatd
    - dmenu
    - dunst
    # - swayr  # AUR

- name: Ensure seatd started and enabled
  become: true
  ansible.builtin.service:
    name: seatd
    state: started
    enabled: true

# - name: Add user to seat group
#   become: false  # "useradd: Permission denied"
#   ansible.builtin.user:
#     name: "{{ lookup('env', 'USER') }}"
#     groups: seat
#     append: true
