---
- name: Update pacman cache
  become: true
  community.general.pacman:
    update_cache: true
  changed_when: false
  when: ansible_os_family == 'Archlinux'

- name: Install Sway
  become: true
  community.general.pacman:
    name:
      - sway
    state: present
  when: ansible_os_family == 'Archlinux'

- name: Install Sway Extras
  become: true
  community.general.pacman:
    name:
      - dunst
      - seatd
      - waybar
      - wayland
      - wayland-protocols
      - xorg-xwayland
    state: present
  when: ansible_os_family == 'Archlinux'

- name: Ensure seatd started and enabled
  become: true
  ansible.builtin.service:
    name: seatd
    state: started
    enabled: true
  when: ansible_os_family == 'Archlinux'
