---
- name: Install Sway
  become: true
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - sway
  tags:
    - sway

- name: Install Sway Extras
  become: true
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - xorg-xwayland
    - conky
    - dmenu
    - dunst
    - feh
  tags:
    - sway
