---
- name: Uninstall Sway
  become: true
  package:
    name:
      - sway
    state: absent
  tags:
    - sway

- name: Destroy ~/.config/sway directory
  become: false
  file:
    path: ~/.config/sway
    state: absent
  tags:
    - sway
