---
- name: Prepare
  hosts: all
  tasks:
    - name: Disable pacman internal sandbox (Arch containers)
      become: true
      ansible.builtin.lineinfile:
        path: /etc/pacman.conf
        line: "DisableSandbox"
        insertafter: "^\\[options\\]"
      when: ansible_os_family == 'Archlinux'

    - name: Upgrade all packages to current (Arch containers)
      become: true
      community.general.pacman:
        upgrade: true
        update_cache: true
      changed_when: false
      when: ansible_os_family == 'Archlinux'
